'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { Layout } from '@/components/layout'
import { BreadcrumbNav } from '@/components/breadcrumb-nav'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Download, BarChart3 } from 'lucide-react'
import { toast } from '@/hooks/use-toast'

interface Report {
  id: string
  timestamp: Date
  predictions: number
  accuracy: { rmse: number; mae: number; r2: number }
  avgConsumption: number
  peakHour: string
}

export default function ReportsPage() {
  const router = useRouter()
  const [reports, setReports] = useState<Report[]>([])

  useEffect(() => {
    const userData = localStorage.getItem('gefcom_user')
    if (!userData) {
      router.push('/login')
      return
    }

    // Load reports from localStorage
    const stored = localStorage.getItem('gefcom_reports')
    if (stored) {
      setReports(JSON.parse(stored))
    }
  }, [router])

  const downloadReport = (report: Report) => {
    const reportData = `
GEFCom Energy Forecasting Report
Generated: ${new Date(report.timestamp).toLocaleString()}

=== SUMMARY ===
Total Predictions: ${report.predictions}
Average Consumption: ${report.avgConsumption.toFixed(2)} MW
Peak Usage Hour: ${report.peakHour}

=== ACCURACY METRICS ===
RMSE: ${report.accuracy.rmse.toFixed(4)}
MAE: ${report.accuracy.mae.toFixed(4)}
R² Score: ${report.accuracy.r2.toFixed(4)}

Generated by GEFCom Energy Forecasting System
    `.trim()

    const blob = new Blob([reportData], { type: 'text/plain' })
    const url = window.URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `gefcom-report-${report.id}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    window.URL.revokeObjectURL(url)

    toast({
      title: 'Success',
      description: 'Report downloaded',
    })
  }

  return (
    <Layout>
      <BreadcrumbNav />
      <div className="space-y-8">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-4xl font-bold mb-2">Reports</h1>
            <p className="text-muted-foreground">
              Download and view prediction reports
            </p>
          </div>
          <Badge variant="outline">{reports.length} reports</Badge>
        </div>

        <Card className="p-6">
          {reports.length === 0 ? (
            <div className="text-center py-12">
              <BarChart3 className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
              <p className="text-muted-foreground mb-4">No reports generated yet</p>
              <p className="text-xs text-muted-foreground">
                Run bulk predictions to generate reports
              </p>
            </div>
          ) : (
            <div className="space-y-3">
              {reports.map((report) => (
                <div key={report.id} className="p-4 border rounded-lg flex items-center justify-between hover:bg-muted/50">
                  <div className="flex-1">
                    <p className="font-medium">
                      {report.predictions} predictions • {new Date(report.timestamp).toLocaleDateString()}
                    </p>
                    <div className="flex gap-2 mt-1 text-xs text-muted-foreground">
                      <span>R²: {report.accuracy.r2.toFixed(3)}</span>
                      <span>•</span>
                      <span>RMSE: {report.accuracy.rmse.toFixed(2)}</span>
                    </div>
                  </div>
                  <Button
                    onClick={() => downloadReport(report)}
                    variant="outline"
                    size="sm"
                    className="gap-2"
                  >
                    <Download className="h-4 w-4" />
                    Download
                  </Button>
                </div>
              ))}
            </div>
          )}
        </Card>
      </div>
    </Layout>
  )
}
